// packages/react-form/src/FormItem.tsx
import React, {
  PropsWithChildren,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { RenderProps, useFormInstance } from './index';
import { FormItemProps } from './interface';
import { useDeepEqualLayoutEffect } from './useDeepEqualEffect';
import { components } from './utils';

const getTriggerType = (rules: FormItemProps['rules']) => {
  const triggerKey = 'onChange';
  if (!rules) return triggerKey;
  return (Array.isArray(rules) ? rules : [rules]).reduce((str, { trigger }) => {
    if (trigger) str = trigger;
    return str;
  }, 'onChange');
};

const FormItem = (props: FormItemProps) => {
  const {
    el,
    field,
    span,
    offset,
    label,
    labelWidth,
    minItemWidth,
    itemClassName,
    itemStyle,
    labelAlign,
    required,
    rules,
    errorMsg,
    onChange,
    children,
    xs,
    sm,
    md,
    lg,
    xl,
    isShow,
    content,
    doNotRegister,
    context: _context,
    rightInfo,
    bottomInfo,
    defaultValue,
    ...other
  } = props;
  const contextData = useFormInstance();
  const [, updateState] = useState({});
  const itemRef = useRef<any>({});

  const getIsShow = (show: FormItemProps['isShow']) => {
    if (typeof show === 'boolean') {
      return show;
    }
    const keys = Object.keys(show?.relyOn ?? {});
    if (keys.length) {
      if (typeof show === 'object') {
        const method = show.relation === 'and' ? 'every' : 'some';
        let _isShow = keys[method]((k) => {
          const val = show.relyOn[k];
          let flag = true;
          if (Array.isArray(val)) {
            flag = val?.includes(contextData.getValue(k));
          } else if (typeof val === 'string') {
            try {
              const fn = new Function(`return ${val}`)();
              flag = fn(contextData.getValue(k), contextData);
            } catch (error) {
              flag = false;
              console.error(error);
            }
          } else {
            flag = val(contextData.getValue(k), contextData);
          }
          return show.notIn ? !flag : flag;
        });
        if (typeof show.external === 'boolean') {
          _isShow =
            show.relation === 'and'
              ? _isShow && show.external
              : _isShow || show.external;
        }
        return _isShow;
      }
    }
    return true;
  };

  const itemInstance = useRef({
    setErrorMsg(errMsg?: string) {
      itemInstance.current.errorMsg = errMsg;
      updateState({});
    },
    setSateShow(flag: boolean) {
      itemInstance.current.show = flag;
      if (field) {
        contextData.clearValidate([field]);
      }
      updateState({});
    },
    errorMsg,
    defaultValue,
    value: (field ? contextData.getValue(field) : other.value) ?? defaultValue,
    show: getIsShow(isShow),
    rules,
  });

  itemInstance.current.rules = rules;

  const isRequired = useMemo(() => {
    if (!rules) return required;
    if (Array.isArray(rules)) return rules.some((item) => item.required);
    return rules.required;
  }, [required, rules]);

  const textAlign = labelAlign ?? contextData.labelAlign;
  const labelStyles = {
    width: labelWidth ?? contextData.labelWidth,
    textAlign: textAlign === 'top' ? 'left' : textAlign,
  };

  const handlerChange = (e: any, ...args: any[]) => {
    let value!: any;
    try {
      if (typeof e?.stopPropagation === 'function') {
        e.stopPropagation();
      }
      value = e.target.value;
    } catch (error) {
      value = e;
    }
    if (field) {
      contextData.onFiledChange(field, {
        value,
        e,
        ...args,
        rules,
        oldVal: itemInstance.current.value,
      });
    }
    onChange?.(e, ...args);
  };

  useEffect(() => {
    if (!field) return;
    return contextData.subscribe(
      [field],
      (k, { value }) => {
        itemInstance.current.value = value;
        updateState({});
      },
      { deep: true },
    );
  }, [field]);

  useLayoutEffect(() => {
    if (field) {
      return contextData.onLifeCycle(field, itemInstance.current);
    }
  }, [field]);

  useLayoutEffect(() => {
    itemInstance.current.setErrorMsg(errorMsg);
  }, [errorMsg]);

  useDeepEqualLayoutEffect(() => {
    if (typeof isShow === 'boolean') {
      itemInstance.current.setSateShow(isShow);
    } else {
      const keys = Object.keys(isShow?.relyOn ?? {});
      if (keys.length) {
        return contextData.subscribe(keys, () => {
          itemInstance.current.setSateShow(getIsShow(isShow));
        });
      }
      itemInstance.current.setSateShow(true);
    }
  }, [isShow]);

  const getChildren = () => {
    let child: any = children ?? el;
    if (child) {
      Object.assign(
        itemRef.current,
        itemInstance.current,
        contextData,
        _context ?? {},
        {
          field,
          labelWidth: labelStyles.width,
          labelAlign: textAlign,
        },
      );
      const propsData: PropsWithChildren<RenderProps> = {
        context: itemRef.current,
        field,
        size: other.size ?? contextData.size,
        disabled: other.disabled ?? contextData.disabled,
        children: content,
        value: itemInstance.current.value,
        ...other,
        onChange: handlerChange,
      };
      const triggerType = getTriggerType(rules) as 'onChange';
      if (field && triggerType) {
        const fn = propsData[triggerType];
        propsData[triggerType] = (...args: any[]) => {
          fn?.(...args);
          contextData.validate([field]);
        };
      }
      if (React.isValidElement<any>(child)) {
        child = React.cloneElement(child, {
          ...child.props,
          ...propsData,
          children: child.props.children ?? content,
        });
      } else if (child.isReactClass) {
        const Comp = child;
        return <Comp {...propsData} />;
      } else if (typeof child === 'function') {
        child = child(propsData);
      } else if (typeof child === 'string' && components[child]) {
        const Comp = components[child];
        return <Comp {...propsData} />;
      }
      return child;
    }
    return itemInstance.current.value;
  };
  const getClassName = () => {
    const str: string[] = ['wxl-form-item'];
    const _span = span ?? contextData.span;
    const _offset = offset ?? contextData.offset;
    const topClass = textAlign === 'top' ? 'wxl-form-item-top' : '';
    const errorClass = itemInstance.current.errorMsg ? 'item_error' : '';
    if (_span) {
      str.push(`col-${_span}`);
    }
    if (_offset) {
      str.push(`col-offset-${_offset}`);
    }
    const arr = ['xs', 'sm', 'md', 'lg', 'xl'];
    arr.forEach((key) => {
      const o = props[key as 'xs'] ?? contextData[key as 'xs'];
      if (!o) return '';
      if (typeof o === 'object') {
        if (o.span) {
          str.push(`col-${key}-${o.span}`);
        }
        if (o.offset) {
          str.push(`col-${key}-offset-${o.offset}`);
        }
      } else {
        str.push(`col-${key}-${o}`);
      }
    });
    if (topClass) {
      str.push(topClass);
    }
    if (errorClass) {
      str.push(errorClass);
    }
    if (itemClassName) {
      str.push(itemClassName);
    }
    return str.join(' ');
  };
  return (
    <div
      className={getClassName()}
      data-field={field}
      style={{
        minWidth: minItemWidth ?? contextData.minItemWidth,
        ...itemStyle,
        display: itemInstance.current.show ? undefined : 'none',
      }}
    >
      {label !== undefined && (
        <label
          title={typeof label === 'string' ? label : ''}
          className={`wxl-form-item-label ${isRequired ? 'required' : ''}`}
          style={labelStyles}
        >
          {label}
        </label>
      )}
      <div className="wxl-form-item-container">
        <div className="wxl-form-item-children">
          <div className="wxl-form-item-com">{getChildren()}</div>
          {rightInfo && (
            <div className="wxl-form-item-rightInfo">{rightInfo}</div>
          )}
        </div>
        {itemInstance.current.errorMsg && (
          <span className="wxl-form-item-error">
            {itemInstance.current.errorMsg}
          </span>
        )}
        {bottomInfo && <>{bottomInfo}</>}
      </div>
    </div>
  );
};
export default React.memo(FormItem);

// packages/vue3-form/src/components/FormItem.vue
<template>
  <div :class="className" :style="style" v-if="show" :data-field="field">
    <div v-bind="labelProps" v-if="label">
      <component :is="label" />
    </div>
    <div class="v3-form-item-container">
      <component
        :is="child"
        v-bind="childProps"
        @update:modelValue="onUpdateModelValue"
      />
      <span class="v3-form-item-error">{{ errorMsg }} </span>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {
  computed,
  inject,
  ref,
  h,
  onBeforeUnmount,
  getCurrentInstance,
  watch,
  isVNode,
  useSlots,
} from 'vue';
import { FormItemProps, FormProps, RegisterRules, Validate } from './interface';
import { components } from './const';

import { get, set } from 'lodash';
let unRegisterRules: Function | undefined;

const context = inject<FormProps>('context', {});
const registerRules = inject<RegisterRules>('registerRules');
const validate = inject<Validate>('validate');
const parentSlots = inject<Record<string, any>>('slots');
const props = defineProps<FormItemProps>();
const slots = useSlots();
const textAlign = computed(() => props.labelAlign ?? context?.labelAlign);
const errorMsg = ref();
const show = ref(true);
const triggerType = computed(() => {
  if (props.field && props.rules) {
    let arr = Array.isArray(props.rules) ? props.rules : [props.rules];
    return arr.find((obj) => obj?.trigger)?.trigger ?? 'oninput';
  }
  return null;
});
const className = computed(() => {
  const str: string[] = ['v3-form-item'];
  const span = props.span ?? context?.span;
  const offset = props.offset ?? context?.offset;
  const topClass = textAlign.value === 'top' ? 'hyk-form-item-top' : '';
  const errorClass = errorMsg.value ? 'item_error' : '';
  if (span) {
    str.push(`col-${span}`);
  }
  if (offset) {
    str.push(`col-offset-${offset}`);
  }
  const arr = ['xs', 'sm', 'md', 'lg', 'xl'];
  arr.forEach((key) => {
    const o = props[key as 'xs'] ?? context?.[key as 'xs'];
    if (!o) return '';
    if (typeof o === 'object') {
      if (o.span) {
        str.push(`col-${key}-${o.span}`);
      }
      if (o.offset) {
        str.push(`col-${key}-offset-${o.offset}`);
      }
    } else {
      str.push(`col-${key}-${o}`);
    }
  });
  if (topClass) {
    str.push(topClass);
  }
  if (errorClass) {
    str.push(errorClass);
  }
  return str.join(' ');
});
const getEl = (el?: FormItemProps['label'], defaultEl = 'div'): any => {
  if (!el) return defaultEl;
  if (isVNode(el)) {
    return el;
  }
  const key = components[el as keyof typeof components];
  if (typeof key === 'object') return key;
  return getCurrentInstance()?.appContext.app.component(key ?? el) ?? defaultEl;
};

const setVal = (e: any) => {
  const val = e?.target?.value ?? e;
  if (props.field) {
    set(context.formData ?? {}, props.field, val);
  }
};
const _validate = () => {
  validate?.([props.field as string])
    .then(() => {
      errorMsg.value = '';
    })
    .catch((errors) => {
      errorMsg.value = errors?.[0]?.message;
    });
};
const onUpdateModelValue = (...args: any[]) => {
  setVal(args[0]);
  props.props?.['onupdate:modelValue']?.(...args);
  _validate();
};
const childProps = computed(() => {
  const value = props.field ? get(context.formData, props.field) : undefined;

  const p = {
    size: context.size,
    disabled: context.disabled,
    ...props.props,
    value,
    modelValue: value,
    oninput(...args: any[]) {
      setVal(args[0]);
      props.props?.oninput?.(...args);
      if (triggerType.value === 'oninput') {
        _validate();
      }
    },
    onchange(...args: any[]) {
      setVal(args[0]);
      props.props?.onchange?.(...args);
      if (triggerType.value === 'onchange') {
        _validate();
      }
    },
  };
  return p;
});
const style = computed(() => {
  return {
    ...props.style,
    minWidth: props.minItemWidth ?? context?.minItemWidth,
  };
});
const child = computed(() => {
  if (props.field && parentSlots?.[props.field]) {
    return parentSlots[props.field];
  }
  const el = (slots as unknown as any).default ?? getEl(props.el);
  return h(
    el,
    null,
    props?.slots ?? (el === 'div' ? childProps.value.value : undefined),
  );
});

const isRequired = computed(() => {
  if (!props.rules) return props.required;
  if (Array.isArray(props.rules))
    return props.rules.some((item) => item.required);
  return props.rules.required;
});
const labelProps = computed(() => {
  return {
    title: typeof props.label === 'string' ? props.label : '',
    class: `v3-form-item-label ${isRequired.value ? 'required' : ''}`,
    style: {
      marginRight: props.label ? undefined : '0px',
      width: props.labelWidth ?? context.labelWidth,
      textAlign: textAlign.value === 'top' ? 'left' : textAlign.value,
    },
  };
});
const label = computed(() => {
  if (props.label === undefined) return;
  const el = getEl(props.label, 'label');
  if (isVNode(el)) return el;
  return h(el, null, props.label as any);
});
watch(
  [() => props.rules, () => props.field, () => show.value],
  () => {
    unRegisterRules?.();
    if (props.field && show.value) {
      unRegisterRules = registerRules?.(props.field, {
        rules: props.rules,
        setError(msg: string) {
          errorMsg.value = msg;
        },
      });
    }
  },
  {
    immediate: true,
  },
);
watch(
  [() => props.props?.value, () => props.field],
  () => {
    if (
      props.field &&
      Object.prototype.hasOwnProperty.call(props.props ?? {}, 'value')
    ) {
      set(context.formData ?? {}, props.field, props.props?.value);
    }
  },
  {
    immediate: true,
  },
);
onBeforeUnmount(() => {
  unRegisterRules?.();
});
</script>
